### ISSUE TITLE
Dear developers

### ISSUE THREAD

**Issue by semzwart** [msaad1999/KLiK-SocialMediaWebsite#1]
When i follow al the instalation steps, and i install this in my webserver correctly with a database and added the tables, first of all the index.php file doesnt show anything in my browser, seconf of all when i register, and i want to login i get an http error 500 server error, and when i want to try to do a password reset i get a sql error, can you please fix these so it is ready to rock n roll thanks so much

**Comment by semzwart** [comment]
Hey,

 

Thanks for your quick response. 

 

I have tried the things you said. But I am not running the site locally, I am running it on my domain, I created the database trough my web server and I connected with it in the dbh.inc.php file. But when I open it there is nothing showing up on the index page, and when I try to register it works fine, but after that when I want to login I get the http 500 error and I cant seem to find the problem… sorry for that.

 

 

Would you be kind to send me a version of the klik social media website that works for a 100%, that has already my details in it.

 

 

So my db connect details are.

 

Host:     rdbms.strato.de

Username :        U3489736

Password:           Jennifers20!@

Dbname              DB3489736

 

 

If you need anymore details of me for it just let me know and ill make sure to send them to you..

 

Could you please let me know something as soon as possible, thanks a lot

 

Sem Zwart 

 

Van: Muhammad Saad <notifications@github.com> 
Verzonden: maandag 4 februari 2019 09:23
Aan: msaad1999/KLiK-SocialMediaWebsite <KLiK-SocialMediaWebsite@noreply.github.com>
CC: semzwart <99054776@mydavinci.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [msaad1999/KLiK-SocialMediaWebsite] Dear developers (#1)

 

Alright, just to be sure, I'm sure you already ensure much of what i'll say, but ill list some things that might be the matter:

1.	make sure u access the .php files through localhost, not by opening them directly in chrome
2.	The 500 server error is generally caused by the server you are currently using. Some measure you can take for that are:

*	If you are using Apache server, make sure it is updated along with the PHP version.
*	make sure you did not accidentally delete any images or files, since that error might also occur if it fails to load a resource.
*	Make sure that any changes you might have done in the source code are error-free (the current code has been repeatedly tested and is free of any Language errors)
*	One more way is to search for that error in your server stack, since some server stacks themselves have a common prevalent issue in their source code.
*	[ Advanced Solution ] Check the error_reporting, display_errors and display_startup_errors settings in your php.ini file. They should be set to E_ALL and "On" respectively (though you should not use display_errors on a production server, so disable this and use log_errors instead if/when you deploy it). You can also change these settings (except display_startup_errors) at the very beginning of your script to set them at runtime (though you may not catch all errors this way):

error_reporting(E_ALL);
ini_set('display_errors', 'On');

After that, restart server.

3.	As for the password reset system, the url for the password change is currently set to access localhost/klik. If your server URL is different, you might have to change the url in the reset-request.inc.php file.
4.	SQL error means either an error in the source code or an error in your SQL version or installation. After hearing your issue, the source code was rechecked but no sql errors were found, so you might want to ensure that your SQL version is updated and that your server/server-stack supports mysqli APIs
5.	Also, if your login screen shows correctly but you are unable to login, i might need more details to understand the problem. Can you provide some screenshots of what is displayed on the screen?

A last solution might be to search these problems (as mentioned before) for your server currently being used, since some server stacks have bugs/problems and only their own developers can solve them.

You can also try deleting the KLiK project and all databases/files related to it, download it again from the repository and try to install it again.

**Comment by msaad1999** [comment]
**First**, modifying an entire project for one user is not really possible, since i cannot attach the .php files here and neither can i attach an edited copy of the project here. Although, what I CAN do and will do is provide the solutions to the problems that i understood after reading your recent reply.

**Second**, you just provided me with sensitive details about your website, which is ALWAYS dangerous. Do make sure that you change all the credentials after this 🙂
I also failed to access or ping the host you mentioned, although there was one with the name of `http://rdbms.sstrato.de` (with an additional 's'). If you did not type the host name wrong and this one is incorrect, i will list the edited files in which you will have to change it back to whatever name your host has.

As for the index page showing nothing, that file automatically redirects a user to the login page if he/she is not logged it. The index page itself is the dashboard, and can only be accessed by logging in. No content being showed implies that the login process is not working correctly, and you might have to contact your `hosting service` to check that as well, since all `tests` on the current source code are running without any issues or errors.

> The http 500 error is an error on the server side and can (in most cases) be resolved only by the hosting service. Even if i provide you the project copy with your details, if the server error is not resolved, it will still not work. I have listed all possible ways to fix it, and the last method is to contact your hosting service to fix it.

## Solutions

1. Make sure your db connect information is correct. The `username` of your domain is different for `phpMyAdmin`, although the password is the same. You can recheck the username inside phpMyAdmin by looking at the `Database Serve` panel on the right side of the screen.

![capture](https://user-images.githubusercontent.com/40332031/52216794-e4d88780-28b8-11e9-81d3-224522cc66fe.PNG)
> The part underlined in red is the username used by your DBMS

2. It is recommended (as mentioned in the ReadMe), that the database you use for KLiK be named klik_database. You can either rename the database or delete it and re-import the database file, since i made changed so that it automatically created and uses a database with a certain name, so no additional step needs to be taken.

3. Change the following URL in on `line # 13` in the `reset-request.inc.php` file to replace `localhost` with your correct domain name
```php
$url = "localhost/klik/create-new-pwd.php?selector=" 
                 . $selector . "&validator=" . bin2hex($token);
```

4. After signing up for a new account, open the `klik_database` inside `phpMyAdmin` and manually verify that the new account is visible in the `users` table, meaning that the registration was successful. 

5. It is not really necessary to get an edited copy of the project with your information. All you need to do is to edit the `dbh.inc.php` and the `reset-request.inc.php` file.
- dbh.inc.php
```
$serverName = "http://rdbms.sstrato.de/";
$dBUsername = "root";
$dBPassword = "example123";
$dBName = "klik_database";
```
> As mentioned before, recheck your username and other credentials first.
- reset-request.inc.php [line # 13]
```
$url = "localhost/klik/create-new-pwd.php?selector=" 
                 . $selector . "&validator=" . bin2hex($token);
```

> Also please provide **Screenshots or Pictures** of what is displayed when you try to access the `index.php` file
