### ISSUE TITLE
Stuck on loading dashboard screen

### ISSUE THREAD

**Issue by Homemadestea58** [msaad1999/KLiK-SocialMediaWebsite#4]
Whenever i login to Klik on my iPad it does not go past the screen of the ball and the bars.

**Comment by msaad1999** [comment]
That means there is probably a connection problem in your project. Try verifying that your database and/or SMTP connections are working. If that does not work out, enable PHP debug in your server and try seeing if any error comes up instead of the infinite loading screen.
If there is no error even then, that again heavily implies that the problem lies in connections rather than the code itself.

**Comment by Homemadestea58** [comment]
Ok
Thank you for your help
