### ISSUE TITLE
Problem in deploying on ubuntu 20.04 platform

### ISSUE THREAD

**Issue by praveenkumar-alpha** [msaad1999/KLiK-SocialMediaWebsite#5]
![15927506578507682209188130768214](https://user-images.githubusercontent.com/58038607/85227548-d29eb100-b3fb-11ea-976f-55488084504e.jpg)
I have followed all the steps mentioned in the installation procedure when I run the website in my localhost I can signup successfully and the data is stored in the database but when I try to login the browser is loading for a long time (continuesly) and the home page is not displayed.

NOTE:
But the exactly the same code works perfectly in the windows environment.

**Comment by ishan-agarwal** [comment]
![Screenshot from 2020-06-22 09-45-07](https://user-images.githubusercontent.com/54311154/85247950-167dce80-b46d-11ea-9c1f-22f1e6b67923.png)
Same problem here :/ (Ubuntu 20.04)

**Comment by praveenkumar-alpha** [comment]
Hope the author will response soon!!!!!

**Comment by praveenkumar-alpha** [comment]
I have found that only the index.php is loading continuesly, other pages after logging in successfully such as events.php, forums,php and polls are working perfectly you can check it out bu giving the path in the address bar of your browser replacing index.php. but I can't find the problem with index.php

**Comment by msaad1999** [comment]
Sorry for the delayed response. I have personally not used/debugged this project on a Linux environment, but i do have an idea of what might be the problem, although i would recommend treating that as a hypothesis instead of a confirmed solution.
- The main difference between the pages that are able to load and the `index.php` page seems to be the loading animation called at page access. The body of the page is made visible once the animation has run for a certain time. Since the animation itself is loaded without problem but does not terminate, it means the main issue is in setting the timeout for the animation and calling the body afterwards.
- From what I have found out, there seems to be no issue with the current implementation of the animation timeout, but it turns out the timeout function itself can be unreliable, especially if the OS/Browser of the server is busy with other tasks. I intend to figure out a better way to implement this for Linux later on, but a temporary solution to make this operable on Linux could be to remove the animation altogether.

> Remove the call to `pageLoad()` within the body tag and comment out the div with `id:loader-logo`. The code block in question is:
```php
<body onload="pageLoad()">
    <div id="loader-wrapper">
        <img src='img/500.png' id='loader-logo'>
        <div class="loader">
            <div class="loader__bar"></div>
            <div class="loader__bar"></div>
            <div class="loader__bar"></div>
            <div class="loader__bar"></div>
            <div class="loader__bar"></div>
            <div class="loader__ball"></div>
        </div>
    </div>
```
This is of course a temporary solution, and as mentioned before, i intend to find a better way to implement this for Linux environments.

**Comment by praveenkumar-alpha** [comment]
I have tried this already by removing the loader animation but it doesn't work for me but removing the div tag with style.display:None worked 50 percent because in DOM None will not display elements but don't know how it is working in windows environment. If I remove the above mentioned div tag navbar profile is working but the recent blogs posts event etc are not displayed.still searching for a better solution.

**Comment by msaad1999** [comment]
Understood. I must clarify that I am currently mired in some work, so I will do my best to find a consistent solution once i get some time.
